services:

  # PostgreSQL
  mas-backend-postgres:
    image: postgres:latest # Also, you could use a specific version like postgres:14.5
    container_name: mas-backend-postgres
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: trust # For auth without SSL certificate setup
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - <volume_path>:/var/lib/postgresql/data/pgdata # Adjust your persistent volume path
    networks:
      - mas-network
    restart: on-failure:3

volumes:
  mas-backend-postgres:
    driver: local

networks:
  mas-network:
    driver: bridge
